# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 617)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidgetFeatures = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetFeatures.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetFeatures.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetFeatures.setObjectName("tableWidgetFeatures")
        self.tableWidgetFeatures.setColumnCount(0)
        self.tableWidgetFeatures.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetFeatures, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidgetObjects = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetObjects.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetObjects.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetObjects.setObjectName("tableWidgetObjects")
        self.tableWidgetObjects.setColumnCount(0)
        self.tableWidgetObjects.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidgetObjects, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.groupBoxPreview = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreview.sizePolicy().hasHeightForWidth())
        self.groupBoxPreview.setSizePolicy(sizePolicy)
        self.groupBoxPreview.setObjectName("groupBoxPreview")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPreview)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBoxPreview)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 565, 231))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_Preview = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_Preview.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Preview.setObjectName("gridLayout_Preview")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSliderScale = QtWidgets.QSlider(self.groupBoxPreview)
        self.horizontalSliderScale.setMinimum(10)
        self.horizontalSliderScale.setMaximum(100)
        self.horizontalSliderScale.setProperty("value", 100)
        self.horizontalSliderScale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderScale.setObjectName("horizontalSliderScale")
        self.horizontalLayout.addWidget(self.horizontalSliderScale)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxPreview, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidgetScenes = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetScenes.sizePolicy().hasHeightForWidth())
        self.tableWidgetScenes.setSizePolicy(sizePolicy)
        self.tableWidgetScenes.setObjectName("tableWidgetScenes")
        self.tableWidgetScenes.setColumnCount(0)
        self.tableWidgetScenes.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidgetScenes, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuScene = QtWidgets.QMenu(self.menubar)
        self.menuScene.setObjectName("menuScene")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCapture = QtWidgets.QAction(MainWindow)
        self.actionCapture.setObjectName("actionCapture")
        self.actionSelect_Device = QtWidgets.QAction(MainWindow)
        self.actionSelect_Device.setObjectName("actionSelect_Device")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuScene.addAction(self.actionCapture)
        self.menuDevice.addAction(self.actionSelect_Device)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuScene.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automator Maker"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Features"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Objects"))
        self.groupBoxPreview.setTitle(_translate("MainWindow", "Preview"))
        self.horizontalSliderScale.setToolTip(_translate("MainWindow", "Scale"))
        self.groupBox.setTitle(_translate("MainWindow", "Scenes"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuScene.setTitle(_translate("MainWindow", "Scene"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCapture.setText(_translate("MainWindow", "Capture"))
        self.actionCapture.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSelect_Device.setText(_translate("MainWindow", "Select Device"))
        self.actionSelect_Device.setShortcut(_translate("MainWindow", "Ctrl+D"))
